Documentation
ShipEngine/firebase-extensions pull request #10
Opened 2021-09-22 02:16 UTC by forksofpower

Validate documentation for all extensions:
- Rates:
  - [ ] preinstall
  - [ ] postinstall
  - [ ] extensions.yaml
  - [ ] readme
- Track Label:
  - [ ] preinstall
  - [ ] postinstall
  - [ ] extensions.yaml
  - [ ] readme
- Validate Address:
  - [ ] preinstall
  - [ ] postinstall
  - [ ] extensions.yaml
  - [ ] readme

2021-09-22 05:02 UTC, andyhite commented on extensions/rates/POSTINSTALL.md
> +        addressResidentialIndicator: 'yes',
This field isn't required

2021-09-22 05:03 UTC, andyhite commented on extensions/rates/POSTINSTALL.md
> +      validateAddress: 'no_validation',
You're missing some important required fields: `carrierId`, `serviceCode`, and `shipDate`.

2021-09-22 05:03 UTC, andyhite commented on extensions/rates/POSTINSTALL.md
> +        phone: '555-555-5555',
`phone` isn't required on the `shipTo`.

2021-09-22 05:03 UTC, andyhite commented on extensions/rates/POSTINSTALL.md
> +      validateAddress: 'no_validation',
Ah, actually – I thought this was the `purchaseLabel` extension. So nevermind.

2021-09-22 19:44 UTC, arielple requested changes
We’ll also need to update a few things in the extension.yaml file from the “Partner guidelines” doc that was shared with us which is slightly different from the reference on the firebase docs site. Specifically: the name includes the firebase product and displayname/description could use a little more color.

name: firestore-shipengine-calculate-rates

displayName: Calculate Shipping Rates with ShipEngine
description:  Calculates real-time shipping rates across 60+ carriers using shipment data written to a Cloud Firestore collection.

2021-09-22 19:44 UTC, arielple commented on extensions/rates/PREINSTALL.md
> +Use this extension to fetch rates for shipments from documents added to a specified Cloud Firestore collection.
Use this extension to calculate real-time shipping rates across 50+ global carriers from documents added to a specified Cloud Firestore collection. [ShipEngine](https://www.shipengine.com/) retrieves all possible rates to help brands, ecommerce platforms, and 3PLs to make the best choice for every shipment, whether shipping cost, time to delivery, carrier capabilities or other factors are most important.

2021-09-24 20:56 UTC, arielple approved these changes

2021-09-29 14:28 UTC, andyhite commented
@forksofpower how close is this to being done?

2021-09-30 18:52 UTC, andyhite approved these changes
Looks good. I'm going to merge this so I can get the extensions published.

2021-09-30 18:52 UTC, merged